import type { KnowledgeGraph } from "./types";

export function buildUaSampleGraph(projectName: string): KnowledgeGraph {
  return {
    version: "1.0.0",
    kind: "codebase",
    project: {
      name: projectName,
      languages: ["TypeScript", "Markdown"],
      frameworks: ["React", "Agent Canvas"],
      description: "Understand-Anything dashboard data boundary for LiquidAIty UA agents.",
      analyzedAt: new Date().toISOString(),
      gitCommitHash: "local",
    },
    nodes: [
      {
        id: "ua-dashboard",
        type: "module",
        name: "UA Dashboard",
        filePath: "Understand-Anything-main/understand-anything-plugin/packages/dashboard/src/App.tsx",
        summary: "The shared Understand-Anything dashboard/canvas host used by all UA agent cards.",
        tags: ["ua", "dashboard", "canvas"],
        complexity: "moderate",
      },
      {
        id: "project-overview",
        type: "file",
        name: "ProjectOverview",
        filePath: "packages/dashboard/src/components/ProjectOverview.tsx",
        summary: "Project summary sidebar for overview and scanner lenses.",
        tags: ["overview"],
        complexity: "simple",
      },
      {
        id: "graph-view",
        type: "module",
        name: "Graph Canvas",
        filePath: "packages/dashboard/src/components/GraphView.tsx",
        summary: "Structural graph canvas with node and edge exploration.",
        tags: ["graph", "structural"],
        complexity: "complex",
      },
      {
        id: "domain-view",
        type: "domain",
        name: "Domain View",
        summary: "Domain graph lens for business flows and cross-domain relationships.",
        tags: ["domain"],
        complexity: "moderate",
        domainMeta: {
          entities: ["Domain", "Flow", "Step"],
          businessRules: ["Use domain mode for domain_analyzer lenses"],
          crossDomainInteractions: ["Shared dashboard store selects the active view mode"],
        },
      },
      {
        id: "analysis-flow",
        type: "flow",
        name: "Analysis Flow",
        summary: "UA analysis moves from source scanning to graph review and guided learning.",
        tags: ["flow"],
        complexity: "moderate",
        domainMeta: {
          entryPoint: "uiLens",
          entryType: "manual",
        },
      },
      {
        id: "lens-step",
        type: "step",
        name: "Lens Selection",
        filePath: "client/src/runtime/uaAgentDefinitions.ts",
        summary: "The selected UA card controls the dashboard view mode.",
        tags: ["lens"],
        complexity: "simple",
      },
      {
        id: "knowledge-view",
        type: "article",
        name: "Knowledge Graph View",
        filePath: "packages/dashboard/src/components/KnowledgeGraphView.tsx",
        summary: "Knowledge graph canvas for article, guide, and assembly lenses.",
        tags: ["knowledge"],
        complexity: "moderate",
        knowledgeMeta: {
          wikilinks: ["ua-dashboard"],
          category: "UA dashboard",
          content: "Article Analyzer, Assemble Reviewer, and Knowledge Graph Guide use the shared knowledge graph view.",
        },
      },
      {
        id: "node-info",
        type: "entity",
        name: "NodeInfo",
        filePath: "packages/dashboard/src/components/NodeInfo.tsx",
        summary: "Right-side node detail inspector from the real UA dashboard.",
        tags: ["inspector"],
        complexity: "moderate",
      },
    ],
    edges: [
      { source: "ua-dashboard", target: "project-overview", type: "contains", direction: "forward", weight: 0.8 },
      { source: "ua-dashboard", target: "graph-view", type: "contains", direction: "forward", weight: 0.9 },
      { source: "ua-dashboard", target: "domain-view", type: "contains", direction: "forward", weight: 0.9 },
      { source: "ua-dashboard", target: "knowledge-view", type: "contains", direction: "forward", weight: 0.9 },
      { source: "domain-view", target: "analysis-flow", type: "contains_flow", direction: "forward", weight: 0.8 },
      { source: "analysis-flow", target: "lens-step", type: "flow_step", direction: "forward", weight: 0.1 },
      { source: "knowledge-view", target: "node-info", type: "related", direction: "forward", weight: 0.6 },
      { source: "graph-view", target: "node-info", type: "related", direction: "forward", weight: 0.6 },
    ],
    layers: [
      {
        id: "dashboard",
        name: "Dashboard",
        description: "Real UA dashboard host components.",
        nodeIds: ["ua-dashboard", "project-overview", "graph-view", "node-info"],
      },
      {
        id: "domain",
        name: "Domain",
        description: "Domain lens components.",
        nodeIds: ["domain-view", "analysis-flow", "lens-step"],
      },
      {
        id: "knowledge",
        name: "Knowledge",
        description: "Knowledge graph lens components.",
        nodeIds: ["knowledge-view"],
      },
    ],
    tour: [
      {
        order: 0,
        title: "Shared Dashboard Host",
        description: "All UA Agent Canvas cards open this shared dashboard host.",
        nodeIds: ["ua-dashboard"],
      },
      {
        order: 1,
        title: "Lens Driven View",
        description: "The connected UA card's uiLens selects the closest real UA dashboard mode.",
        nodeIds: ["lens-step", "domain-view", "knowledge-view"],
      },
    ],
  };
}
