DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mcp') THEN
    CREATE ROLE mcp LOGIN PASSWORD 'mcp_password';
  ELSE
    ALTER ROLE mcp PASSWORD 'mcp_password';
  END IF;
END
$do$;

GRANT CONNECT ON DATABASE liquidaity TO mcp;
GRANT USAGE  ON SCHEMA public, ag_catalog TO mcp;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mcp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mcp;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ag_catalog TO mcp;
ALTER DEFAULT PRIVILEGES IN SCHEMA ag_catalog
  GRANT EXECUTE ON FUNCTIONS TO mcp;
