"""Generate versioned MCP schemas and integration inputs from the registered tools."""
from __future__ import annotations

import argparse
import hashlib
import inspect
import json
from pathlib import Path
from pprint import pformat
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def build_contract() -> dict:
    from engraphis.mcp_server import classic_mcp, smart_mcp

    surfaces = {}
    for name, server in (("smart", smart_mcp), ("classic", classic_mcp)):
        surfaces[name] = [
            # Python 3.13+ removes common indentation from compiled docstrings.
            # Normalize only that margin, retaining nested examples and all schema data.
            {"name": tool.name, "description": inspect.cleandoc(tool.description),
             "inputSchema": tool.parameters,
             "annotations": tool.annotations.model_dump(
                 mode="json", by_alias=True, exclude_none=True,
             )
             if tool.annotations else {}}
            for _, tool in sorted(server._tool_manager._tools.items())
        ]
    encoded = json.dumps(surfaces, sort_keys=True, separators=(",", ":")).encode()
    return {"schema": "engraphis-mcp-contract/v1", "sha256": hashlib.sha256(encoded).hexdigest(),
            "surfaces": surfaces}


def artifacts(contract: dict) -> dict[Path, str]:
    schemas = {tool["name"]: tool["inputSchema"] for tool in contract["surfaces"]["smart"]}
    return {
        ROOT / "docs/MCP_CONTRACT.json": json.dumps(contract, indent=2, sort_keys=True) + "\n",
        ROOT / "integrations/pi/src/generated-contract.ts":
            "// Generated by scripts/export_mcp_contract.py. Do not edit.\n"
            "export const SMART_SCHEMAS = " + json.dumps(schemas, indent=2, sort_keys=True) + " as const;\n",
        ROOT / "integrations/prime_agent/src/engraphis_prime_agent/_contract.py":
            '"""Generated by scripts/export_mcp_contract.py. Do not edit."""\n'
            "SMART_SCHEMAS = " + pformat(schemas, sort_dicts=True, width=100) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in artifacts(build_contract()).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(expected)
    if stale:
        print("MCP contract drift: " + ", ".join(stale))
        return 1
    print("MCP contract check: OK" if args.check else "MCP contract exported")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
