// Generated by scripts/export_mcp_contract.py. Do not edit.
export const SMART_SCHEMAS = {
  "engraphis_conflict_review": {
    "properties": {
      "limit": {
        "default": 50,
        "description": "Max items to return.",
        "maximum": 100,
        "minimum": 1,
        "title": "Limit",
        "type": "integer"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repo scope.",
        "title": "Repo"
      },
      "workspace": {
        "default": "default",
        "description": "Workspace to review.",
        "maxLength": 200,
        "title": "Workspace",
        "type": "string"
      }
    },
    "title": "engraphis_conflict_reviewArguments",
    "type": "object"
  },
  "engraphis_discover_actions": {
    "properties": {
      "category": {
        "default": "",
        "description": "Optional area: memory, governance, code, audit, or ops.",
        "maxLength": 100,
        "title": "Category",
        "type": "string"
      },
      "intent": {
        "default": "any",
        "description": "Side effect: any, read, write, admin, or destructive.",
        "pattern": "^(any|read|write|admin|destructive)$",
        "title": "Intent",
        "type": "string"
      },
      "limit": {
        "default": 1,
        "description": "Number of ranked actions to return.",
        "maximum": 3,
        "minimum": 1,
        "title": "Limit",
        "type": "integer"
      },
      "task": {
        "description": "Describe the capability; do not paste memory content.",
        "maxLength": 2000,
        "minLength": 1,
        "title": "Task",
        "type": "string"
      }
    },
    "required": [
      "task"
    ],
    "title": "engraphis_discover_actionsArguments",
    "type": "object"
  },
  "engraphis_execute_action": {
    "properties": {
      "arguments": {
        "additionalProperties": true,
        "description": "Arguments matching its schema.",
        "title": "Arguments",
        "type": "object"
      },
      "capability_id": {
        "description": "Capability id from discover_actions.",
        "maxLength": 128,
        "minLength": 8,
        "title": "Capability Id",
        "type": "string"
      },
      "schema_digest": {
        "description": "Schema digest from discovery.",
        "maxLength": 128,
        "minLength": 8,
        "title": "Schema Digest",
        "type": "string"
      }
    },
    "required": [
      "capability_id",
      "schema_digest",
      "arguments"
    ],
    "title": "engraphis_execute_actionArguments",
    "type": "object"
  },
  "engraphis_execute_read": {
    "properties": {
      "arguments": {
        "additionalProperties": true,
        "description": "Arguments matching its schema.",
        "title": "Arguments",
        "type": "object"
      },
      "capability_id": {
        "description": "Capability id from discover_actions.",
        "maxLength": 128,
        "minLength": 8,
        "title": "Capability Id",
        "type": "string"
      },
      "schema_digest": {
        "description": "Schema digest from discovery.",
        "maxLength": 128,
        "minLength": 8,
        "title": "Schema Digest",
        "type": "string"
      }
    },
    "required": [
      "capability_id",
      "schema_digest",
      "arguments"
    ],
    "title": "engraphis_execute_readArguments",
    "type": "object"
  },
  "engraphis_get_memory": {
    "properties": {
      "memory_id": {
        "description": "Memory id.",
        "maxLength": 200,
        "minLength": 1,
        "title": "Memory Id",
        "type": "string"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repo scope.",
        "title": "Repo"
      },
      "workspace": {
        "default": "default",
        "description": "Memory workspace.",
        "maxLength": 200,
        "title": "Workspace",
        "type": "string"
      }
    },
    "required": [
      "memory_id"
    ],
    "title": "engraphis_get_memoryArguments",
    "type": "object"
  },
  "engraphis_recall_context": {
    "properties": {
      "allow_remote": {
        "default": false,
        "title": "Allow Remote",
        "type": "boolean"
      },
      "data_classification": {
        "anyOf": [
          {
            "maxLength": 16,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Data Classification"
      },
      "format": {
        "default": "full",
        "description": "full or gist.",
        "title": "Format",
        "type": "string"
      },
      "k": {
        "anyOf": [
          {
            "maximum": 50,
            "minimum": 1,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 50,
        "description": "Count.",
        "title": "K"
      },
      "packing_mode": {
        "default": "legacy",
        "title": "Packing Mode",
        "type": "string"
      },
      "query": {
        "description": "Question.",
        "maxLength": 100000,
        "minLength": 1,
        "title": "Query",
        "type": "string"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repo.",
        "title": "Repo"
      },
      "retrieval_recipe": {
        "default": "default",
        "title": "Retrieval Recipe",
        "type": "string"
      },
      "session_id": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional active session.",
        "title": "Session Id"
      },
      "token_budget": {
        "anyOf": [
          {
            "maximum": 32768,
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 1024,
        "description": "Token cap.",
        "title": "Token Budget"
      },
      "workspace": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional workspace.",
        "title": "Workspace"
      }
    },
    "required": [
      "query"
    ],
    "title": "smart_recall_contextArguments",
    "type": "object"
  },
  "engraphis_remember": {
    "properties": {
      "claim_kind": {
        "default": "",
        "description": "Optional claim predicate/category (e.g. 'configured_value').",
        "maxLength": 200,
        "title": "Claim Kind",
        "type": "string"
      },
      "content": {
        "description": "Durable fact, decision, preference, or procedure.",
        "maxLength": 100000,
        "minLength": 1,
        "title": "Content",
        "type": "string"
      },
      "exact_value": {
        "anyOf": [
          {
            "maxLength": 4096,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional verbatim source value to copy exactly.",
        "title": "Exact Value"
      },
      "exact_value_type": {
        "default": "literal",
        "description": "Literal type: literal, string, identifier, path, number, date, enum, or json.",
        "maxLength": 32,
        "title": "Exact Value Type",
        "type": "string"
      },
      "importance": {
        "default": 0.0,
        "description": "Salience 0 to 1.",
        "maximum": 1.0,
        "minimum": 0.0,
        "title": "Importance",
        "type": "number"
      },
      "mtype": {
        "default": "semantic",
        "description": "Type: semantic, episodic, procedural, or working.",
        "title": "Mtype",
        "type": "string"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repo.",
        "title": "Repo"
      },
      "session_id": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional active session.",
        "title": "Session Id"
      },
      "subject_key": {
        "default": "",
        "description": "Optional stable claim subject (e.g. 'api.rate_limit'); keyed supersession is deterministic.",
        "maxLength": 1000,
        "title": "Subject Key",
        "type": "string"
      },
      "workspace": {
        "anyOf": [
          {
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Chosen workspace; omit for session or project routing.",
        "title": "Workspace"
      }
    },
    "required": [
      "content"
    ],
    "title": "smart_rememberArguments",
    "type": "object"
  },
  "engraphis_session": {
    "properties": {
      "action": {
        "default": "start",
        "description": "Start/resume, or end with handoff.",
        "title": "Action",
        "type": "string"
      },
      "agent": {
        "default": "",
        "description": "Optional agent.",
        "maxLength": 200,
        "title": "Agent",
        "type": "string"
      },
      "force_new": {
        "default": false,
        "description": "Start only: create a session even if this task is already active.",
        "title": "Force New",
        "type": "boolean"
      },
      "goal": {
        "default": "",
        "description": "Optional goal.",
        "maxLength": 1000,
        "title": "Goal",
        "type": "string"
      },
      "open_threads": {
        "anyOf": [
          {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Unresolved follow-ups.",
        "title": "Open Threads"
      },
      "outcome": {
        "default": "",
        "description": "Outcome label.",
        "maxLength": 1000,
        "title": "Outcome",
        "type": "string"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repo.",
        "title": "Repo"
      },
      "session_id": {
        "default": "",
        "description": "End ID or exact ended resume source; same owner/scope, no fallback.",
        "maxLength": 200,
        "title": "Session Id",
        "type": "string"
      },
      "summary": {
        "default": "",
        "description": "Final handoff.",
        "maxLength": 100000,
        "title": "Summary",
        "type": "string"
      },
      "token_budget": {
        "default": 512,
        "description": "Start context token budget.",
        "maximum": 32768,
        "minimum": 0,
        "title": "Token Budget",
        "type": "integer"
      },
      "workspace": {
        "anyOf": [
          {
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Chosen workspace; omit for saved project routing.",
        "title": "Workspace"
      }
    },
    "title": "engraphis_sessionArguments",
    "type": "object"
  },
  "engraphis_update_memory": {
    "properties": {
      "actor": {
        "default": "user",
        "description": "Local actor label; team mode uses caller identity.",
        "maxLength": 200,
        "title": "Actor",
        "type": "string"
      },
      "importance": {
        "anyOf": [
          {
            "maximum": 1.0,
            "minimum": 0.0,
            "type": "number"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional importance 0 to 1.",
        "title": "Importance"
      },
      "memory_id": {
        "description": "Memory id.",
        "maxLength": 200,
        "minLength": 1,
        "title": "Memory Id",
        "type": "string"
      },
      "mtype": {
        "anyOf": [
          {
            "maxLength": 50,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional type: working|episodic|semantic|procedural.",
        "title": "Mtype"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repo scope.",
        "title": "Repo"
      },
      "title": {
        "anyOf": [
          {
            "maxLength": 500,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional title.",
        "title": "Title"
      },
      "workspace": {
        "default": "default",
        "description": "Memory workspace.",
        "maxLength": 200,
        "title": "Workspace",
        "type": "string"
      }
    },
    "required": [
      "memory_id"
    ],
    "title": "engraphis_update_memoryArguments",
    "type": "object"
  }
} as const;
